server:
  port: 8988

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  
logging:
  level:
    com:
      netflix:
        eureka: DEBUG
        discovery: DEBUG